### ISSUE TITLE
Memory problem with large amount of objects and changing materials

### ISSUE THREAD

**Issue by TontonTremblay** [owl-project/ViSII#11]
![image](https://user-images.githubusercontent.com/5629088/83181413-b5ffa980-a0d9-11ea-8758-811d4615a9f6.png)
run this script, https://github.com/owl-project/ViSII/blob/dr/install/simple_animation.py you should get the error around frame 100.

**Comment by n8vm** [comment]
@TontonTremblay could you test this again with the new version of ViSII (alpha 7) and let me know if it still gives you troubles?

**Comment by n8vm** [comment]
I believe this problem is now fixed. Closing.
