### ISSUE TITLE
A few installation issues using artifact 

### ISSUE THREAD

**Issue by GuanyaShi** [owl-project/ViSII#28]
When I installed ViSII using artifact, I met some issues. Here are some solutions:

First, make sure `VISII_HOME` includes the directory that contains the artifact files. Then add these lines to your `.bashrc`:

`export PATH="${PATH}:${VISII_HOME}"`
`export PYTHONPATH=${VISII_HOME}`
`export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${VISII_HOME}"`

(1) If you are using conda, make sure your `LD_LIBRARY_PATH` includes anaconda libraries. One way to guarantee that is to add something like this line in your `.bashrc`:
`export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/guanya/anaconda3/lib"`

(2) Make sure your NVIDIA driver and CUDA are updated. See https://ingowald.blog/installing-the-latest-nvidia-driver-cuda-and-optix-on-linux-ubuntu-18-04/ about how to install the latest NVIDIA driver and CUDA on Ubuntu. For me (GTX 1080), my driver version is 450.36.06 and my CUDA version is 11.0. You can check them using `nvidia-smi` and `nvcc --version`.

(3) One way to check the installation is to do
`import visii`
`visii.initialize_interactive()`
in Python. You will see a box like this if installing succesfully.
![Screenshot from 2020-06-25 00-20-11](https://user-images.githubusercontent.com/26674297/85798081-b6e42500-b6f1-11ea-895a-4222b97a59c1.png)

**Comment by n8vm** [comment]
So I've made a little progress on this. 

On development, the artifacts that are uploaded now contain .whl files, which can be installed with pip.
Something like `pip install visii-0.1.dev1+g360b63e-cp27-cp27mu-linux_x86_64.whl`

This should install visii to a location which is already on your path / python path, although it needs testing. 

I'm thinking when it comes to missing an Nvidia driver, I might open a separate issue to tackle that.

**Comment by n8vm** [comment]
Most all of the above issues have been addressed now that we support distribution using pip. We should open a separate issue to tackle that Nvidia driver thing if that remains an issue.
