### ISSUE TITLE
Expose renderer random seed

### ISSUE THREAD

**Issue by jmunkberg** [owl-project/ViSII#35]
When generating training data for, e.g., denoising, I want to be able to initialize the render with different seeds for the noisy input vs. reference image, to ensure that the two renders of the same frame use uncorrelated random numbers.

**Comment by n8vm** [comment]
This has been added in development. When calling either render_data or render_to_png, etc, there is an optional "seed" parameter which can be used to make unique output images with uncorrelated random numbers. Should be available in alpha 7.
