### ISSUE TITLE
STL loading

### ISSUE THREAD

**Issue by TontonTremblay** [owl-project/ViSII#46]
Or maybe an example from creating a mesh from raw data. or maybe a stl loading from python to visii. Or stl loading directly in visii.

**Comment by n8vm** [comment]
Issue with STL's is that they do not come with texture coordinates or shading normals. So it might be best to load STLs in python, and then have the user compute those shading normals and texture coordinates.

**Comment by TontonTremblay** [comment]
I think we decided to do that, open3d does a good job at loading stl. I will make an example of that.
