### ISSUE TITLE
can you load scenes from pybullet?

### ISSUE THREAD

**Issue by xinleipan** [owl-project/ViSII#56]
So I have scenes in pybullet saved by pybullet.saveWorld function, is there a simple way to load this into ViSII? Or I have to convert each object in the scene into obj file and record their positions and orientations and recreate them?

**Comment by n8vm** [comment]
Hi xinleipan, 

Sorry for the late response. You might be able to also load the data through pybullet and then use the mesh.create_from_data function to avoid saving out OBJ files. In the future, we might start curating python scripts to handle loading different file formats/setups like these. However, for the time being, we do not currently have a direct pybullet scene importer on the roadmap.
