### ISSUE TITLE
loading a texture from raw data is quite slow

### ISSUE THREAD

**Issue by TontonTremblay** [owl-project/ViSII#63]
just looking into it.

**Comment by n8vm** [comment]
Did some digging. Looks like SWIG is looping through the raw python list, checking to see if each item is a number before inserting into some linked list. We can look into accepting numpy arrays directly to hopefully speed up the wrapper code

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.

**Comment by n8vm** [comment]
Should be fixed in the next version of visii. Make sure to pass numpy arrays directly into the create_from_data function instead of a raw python list for best performance.
