### ISSUE TITLE
error in helloworld

### ISSUE THREAD

**Issue by liyi14** [owl-project/ViSII#74]
The error message is:
> Optix call (optixDenoiserCreate(optixContext, &options, &OD.denoiser)) failed with code 7001 (line 711)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
Aborted (core dumped)

I just call `pip install visii` and `python 00.helloworld.py`.
I am using python 3.7 on ubuntu 16.04, with nvidia driver 440.44, cuda 10.0 and RTX 2080Ti.
Is there any requirements I do not match?

**Comment by n8vm** [comment]
Hey Liyi, yeah this is pretty strange. Code 7001 stands for OPTIX_ERROR_INVALID_VALUE, although I'm not sure why that would be.

Your environment looks good to me, although I haven't tested on Ubuntu 16.04 yet. I've only tested on 18.04, 20.04, and windows.

Can you use the OptiX denoiser inside Blender? 

I don't suppose you could test on Ubuntu 20.04 to determine if it's OS related, could you?

**Comment by n8vm** [comment]
![image](https://user-images.githubusercontent.com/13104331/97896884-ee438d80-1cf2-11eb-8415-ab9349e16826.png)

I just noticed that on line 708 there, it seems I'm not setting the pixelFormat (likely got commented out during testing with a newer version of the denoiser). It's possible that on some systems, this value does not default to 0. I can try commenting that line back in and upload a minor update to pip. Perhaps that will fix your issue?

**Comment by n8vm** [comment]
Okay, @liyi14 I uploaded an updated version of visii to pip with the pixelFormat line above commented back in. Could you check to see if you still get that error message after updating your installation of visii?

**Comment by liyi14** [comment]
Hi @n8vm , Thanks for you quick reply!
What's the pip source you uploaded to? I tried `pip install visii -i https://pypi.python.org/simple` but didn't find the new version.
> Looking in indexes: https://pypi.python.org/simple
Requirement already satisfied: visii in /home/yili/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages (0.1.0a10)

**Comment by n8vm** [comment]
I'm not super familiar with python sources. I think we just upload to simple at the moment. 

I seem to be able to see alpha 11 of visii here: https://pypi.org/project/visii/ so it does seem to have uploaded correctly. 
Could you try doing `pip install —upgrade visii` and see if that updates to alpha 11? You might also need to update your version of pip first.

**Comment by liyi14** [comment]
Oh yeah, after I update pip-19 to pip-20, and use the parameter `--upgrade`, it manages to find the alpha 11.
And I have tried many examples and it works well!
Thank you for your help and for this amazing project!

**Comment by n8vm** [comment]
🎉🎉🎉

Let us know if you run into any other issues!
