### ISSUE TITLE
confusing/wrong arrayObjects error message?

### ISSUE THREAD

**Issue by ingowald** [owl-project/ViSII#78]
every time cmake runs on visii it reports
WARNENABLING FPIC
WARNNumpy Include Dir is: 
WARN/usr/lib/python3/dist-packages/numpy/core/include
ERRORERROR, arrayObject does not exist!

but apparently it builds just fine w/o the arrayObject (whatever it might be)

**Comment by n8vm** [comment]
Whups. This warning came from a CI debugging session. I’ll make sure to remove this false error before closing
