### ISSUE TITLE
(u,v) coordinate error in meta_data_exporting example

### ISSUE THREAD

**Issue by manuelli** [owl-project/ViSII#79]
Changing the [height and width parameters](https://github.com/owl-project/ViSII/blob/master/examples/09.meta_data_exporting.py#L16) in the meta data exporting example to have a non-square image results in incorrect meta data images (e.g. depth) being extracted. I am using `--width 640 --height 480`. In this case `depth.png` is `480 x 640` image instead of `640 x 480`.

For reference here is the RGB image

![img](https://user-images.githubusercontent.com/5898488/98887552-06ca4b00-244b-11eb-8cb3-8c4c60773714.png)

and the depth image

![depth](https://user-images.githubusercontent.com/5898488/98886628-4859f680-2449-11eb-96e6-a79e2509a7c5.png)

I believe this is due to an error in reshaping the `depth_array` in [this line](https://github.com/owl-project/ViSII/blob/master/examples/09.meta_data_exporting.py#L128). It currently reads

```
depth_array = np.array(depth_array).reshape(opt.width,opt.height,4)
```

Changing the order of `height` and `width` fixes the issue and produces correct depth images

```
depth_array = np.array(depth_array).reshape(opt.height,opt.width,4)
```

![depth](https://user-images.githubusercontent.com/5898488/98887424-cec30800-244a-11eb-9b37-060cd6006c6d.png)

Given this I am not sure why the original example worked (even with a square image) since it seems like height and width may still have been swapped in the original example.

Of course the same fix needs to be applied to the other metadata fields as well (normals, positions, segmentations, etc.).

**Comment by n8vm** [comment]
Oof, good catch. I’ll make sure to get this fixed before the next merge into master. 

We’ll actually likely be updating this example to use the newer visii.render_to_file API, which supports saving raw segmentations as EXR files with signed 32-bit float channels. There are other examples though where we probably make a similar mistake.

**Comment by n8vm** [comment]
These examples have since been updated to use the newer data exporter, so I'm closing this issue. Thanks for the help
