### ISSUE TITLE
Wrong package name in requirements.txt

### ISSUE THREAD

**Issue by swtyree** [owl-project/ViSII#89]
Hi all, I think that the reference to `PIL` in `examples/requirements.txt` should instead be `pillow`.

https://github.com/owl-project/ViSII/blob/1e69f93f1e5bdf647e55e7570a47cb1b70606822/examples/requirements.txt#L5

**Comment by n8vm** [comment]
Ah, good catch. Should be fixed on devel now, and merged into master soon.
